### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by emec2023** [chathumal93/Pytorch-UNet-Flood-Segmentation#2]
Please provide the python version for which all the requirements will work

**Comment by chathumal93** [comment]
You can try >=3.7, <=3.10

**Comment by emec2023** [comment]
Thank you very much for your reply. We are having difficulty of a python version that will meet all the requirements of the requirements.txt file. If you could let us know which python version worked for you There is no separate ee library assuming installing the earthengine_api==0.1.345 will be sufficient. Also assuming we will have to install cuda 11.6 with the following command
CUDA 11.6
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia

Requirements
earthengine_api==0.1.345
ee==0.4
matplotlib==3.5.2
numpy==1.21.5
pandas==1.4.4
protobuf==4.22.1
pyproj==3.4.1
rasterio==1.3.6
restee==0.0.3
torch==1.13.1+cu116
torchvision==0.14.1+cu116
tqdm==4.64.1
